all:
#	javac ParkedCar.java
#	javac ParkingMeter.java
#	javac PoliceOfficer.java
#	javac ParkingTicket.java
#	javac CarTest.java
#	java CarTest
#	rm *.class
	javac Coin.java
	javac Test.java
	java Test
	rm *.class
